"""Snapshot + market-data loaders.

The site reads model-derived data from data/snapshot.json — never the live Excel model.
Snapshot is regenerated by regenerate_scenarios.py (Refresh button on owner's machine).
Live yfinance price + intraday traces are fetched at request time and not snapshotted.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import streamlit as st
import yfinance as yf

LIVE_MODEL = Path(
    r"C:\Users\JoshuaLehrman\Wolf Hill Capital Management LLC\Shared - Documents\Josh\COKE\Models\WH COKE Model v04.29.2026.xlsx"
)
SNAPSHOT_FILE = Path(__file__).parent / "data" / "snapshot.json"
MARKET_DATA_FILE = Path(__file__).parent / "data" / "market_data.json"
TICKER = "COKE"


def _market_data_mtime() -> float:
    try:
        return MARKET_DATA_FILE.stat().st_mtime
    except FileNotFoundError:
        return 0.0


@st.cache_data(show_spinner=False)
def _load_market_data_cached(mtime: float) -> dict | None:
    if not MARKET_DATA_FILE.exists():
        return None
    return json.loads(MARKET_DATA_FILE.read_text())


def _load_market_data() -> dict | None:
    return _load_market_data_cached(_market_data_mtime())


def _snapshot_mtime() -> float:
    try:
        return SNAPSHOT_FILE.stat().st_mtime
    except FileNotFoundError:
        return 0.0


def load_snapshot() -> dict:
    return _load_snapshot_cached(_snapshot_mtime())


@st.cache_data(show_spinner=False)
def _load_snapshot_cached(mtime: float) -> dict:
    """mtime is included in the cache key (no underscore prefix) so any change to
    snapshot.json on disk auto-busts the cache on the next call."""
    if not SNAPSHOT_FILE.exists():
        raise FileNotFoundError(
            f"{SNAPSHOT_FILE} not found. Run regenerate_scenarios.py to capture the model."
        )
    return json.loads(SNAPSHOT_FILE.read_text())


def snapshot_captured_at() -> datetime | None:
    snap = load_snapshot()
    ts = snap.get("_captured_at")
    if not ts:
        return None
    try:
        return datetime.fromisoformat(ts)
    except ValueError:
        return None


def load_summary(scenario: str = "Base") -> dict:
    """Return summary dict for the chosen scenario, formatted to match the prior schema."""
    snap = load_snapshot()
    static = snap["static"]
    scen = snap["scenarios"][scenario]
    return {
        "years": static["years"],
        "revenue": scen["revenue"],
        "revenue_yoy": scen["revenue_yoy"],
        "ebitda": scen["ebitda"],
        "ebitda_margin": scen["ebitda_margin"],
        "ebitda_yoy": scen["ebitda_yoy"],
        "eps": scen["eps"],
        "eps_yoy": scen["eps_yoy"],
        "valuation": {"years": static["years"], **scen["valuation"]},
        "cap_table_static": static["cap_table_static"],
        "return_eps": scen["return_eps"],
        "return_ebitda": scen["return_ebitda"],
    }


def load_segment_build() -> dict:
    return load_snapshot()["segment_build"]


def load_cogs_sensitivity() -> dict:
    return load_snapshot()["cogs_sensitivity"]


@st.cache_data(ttl=300, show_spinner=False)
def load_live_price() -> float:
    md = _load_market_data()
    if md is not None and md.get("live_price") is not None:
        return float(md["live_price"])
    t = yf.Ticker(TICKER)
    info = t.info
    p = info.get("regularMarketPrice") or info.get("currentPrice")
    if p is None:
        hist = t.history(period="1d")
        p = float(hist["Close"].iloc[-1])
    return float(p)


@st.cache_data(ttl=900, show_spinner=False)
def load_stock_history(period: str = "max") -> dict:
    md = _load_market_data()
    if md is not None and period == "1y" and md.get("stock_history_1y"):
        h = md["stock_history_1y"]
        return {
            "dates": [datetime.fromisoformat(d) for d in h["dates"]],
            "close": [float(c) for c in h["close"]],
        }
    t = yf.Ticker(TICKER)
    hist = t.history(period=period, interval="1d")
    if hist.empty:
        return {"dates": [], "close": []}
    return {
        "dates": [d.to_pydatetime() for d in hist.index],
        "close": [float(c) for c in hist["Close"]],
    }


@st.cache_data(ttl=300, show_spinner=False)
def load_intraday(period: str, interval: str) -> dict:
    t = yf.Ticker(TICKER)
    hist = t.history(period=period, interval=interval)
    if hist.empty:
        return {"dates": [], "close": []}
    return {
        "dates": [d.to_pydatetime() for d in hist.index],
        "close": [float(c) for c in hist["Close"]],
    }


@st.cache_data(ttl=86400, show_spinner=False)
def load_oil_quarterly() -> dict:
    """Quarterly close of WTI futures from yfinance, 2016-present."""
    t = yf.Ticker("CL=F")
    hist = t.history(start="2016-01-01", interval="3mo")
    if hist.empty:
        return {"quarters": [], "close": []}
    quarters = []
    for d in hist.index:
        q = (d.month - 1) // 3 + 1
        quarters.append(f"Q{q} {str(d.year)[-2:]}")
    return {"quarters": quarters, "close": [float(c) for c in hist["Close"]]}


def load_commodities_daily(years: int = 3) -> dict:
    """Daily close for CME Midwest US Aluminum (ALI=F, $/MT) + WTI (CL=F, $/bbl)
    over the trailing N years. Aluminum is quoted directly in USD/metric ton on CME.
    """
    md = _load_market_data()
    if md is not None and years == 3 and md.get("commodities_daily_3y"):
        return md["commodities_daily_3y"]

    from datetime import datetime, timedelta
    start = (datetime.utcnow() - timedelta(days=int(years * 365.25) + 30)).strftime("%Y-%m-%d")

    al = yf.Ticker("ALI=F").history(start=start, interval="1d")
    wti = yf.Ticker("CL=F").history(start=start, interval="1d")

    al_dates = [d.strftime("%Y-%m-%d") for d in al.index] if not al.empty else []
    al_close_mt = [float(c) for c in al["Close"]] if not al.empty else []

    wti_dates = [d.strftime("%Y-%m-%d") for d in wti.index] if not wti.empty else []
    wti_close = [float(c) for c in wti["Close"]] if not wti.empty else []

    return {
        "aluminum": {"dates": al_dates, "close_per_mt": al_close_mt},
        "wti": {"dates": wti_dates, "close_per_bbl": wti_close},
    }


def load_core_cpi_quarterly() -> dict:
    """Quarterly Core CPI (CPILFESL, FRED) from market_data.json. Empty dict on miss."""
    md = _load_market_data()
    if md is None or not md.get("core_cpi_quarterly"):
        return {"quarters": [], "core_cpi": []}
    return md["core_cpi_quarterly"]


def apply_live_price_to_returns(summary: dict, live_price: float) -> dict:
    """Recompute return_eps / return_ebitda 'ret' off live price.

    The model captures returns against its own price-of-record (D7), which lags
    intraday moves and goes stale between snapshots. EPS targets and EBITDA-derived
    price targets are independent of current price, so only the return % needs to
    be redrawn off the live price.
    """
    if not live_price or live_price <= 0:
        return summary
    out = dict(summary)
    for kind in ("return_eps", "return_ebitda"):
        rows = summary.get(kind, [])
        out[kind] = [
            {**r, "ret": (r["target"] / live_price - 1) if r.get("target") is not None else r.get("ret")}
            for r in rows
        ]
    return out


def derive_cap_table(static: dict, live_price: float) -> dict:
    market_cap = live_price * static["diluted_shares"]
    net_debt = static["total_debt"] - static["cash"]
    enterprise_value = market_cap + net_debt + static["nci"]
    return {
        "price": live_price,
        "diluted_shares": static["diluted_shares"],
        "market_cap": market_cap,
        "total_debt": static["total_debt"],
        "cash": static["cash"],
        "net_debt": net_debt,
        "nci": static["nci"],
        "enterprise_value": enterprise_value,
    }
