"""Regenerate Bull/Base/Bear scenarios by flipping Summary!D4 in the live Excel model.

Uses Excel COM (win32com) to open the model, set the scenario switcher to each value,
trigger a recalc, read the Summary outputs (Revenue / EBITDA / EPS for 2022-2029), and
write the captured arrays into data/scenarios.json. Closes Excel without saving so the
model file is never modified.

Run from the Site/ directory whenever you've updated Bull/Bear assumptions in the model:
    python regenerate_scenarios.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import win32com.client as win32

LIVE_MODEL = Path(
    r"C:\Users\JoshuaLehrman\Wolf Hill Capital Management LLC\Shared - Documents\Josh\COKE\Models\WH COKE Model v04.29.2026.xlsx"
)
SCENARIOS_FILE = Path(__file__).parent / "data" / "scenarios.json"

SCENARIO_VALUES = [("Bull", "1 - Bull"), ("Base", "2 - Base"), ("Bear", "3 - Bear")]
YEAR_COLS = ["G", "H", "I", "J", "K", "L", "M", "N"]  # 2022-2029 on Summary tab
ROWS = {"revenue": 4, "ebitda": 12, "eps": 22}


def capture_outputs(ws) -> dict[str, list[float]]:
    out = {}
    for key, r in ROWS.items():
        out[key] = [float(ws.Range(f"{c}{r}").Value or 0) for c in YEAR_COLS]
    return out


def main() -> int:
    if not LIVE_MODEL.exists():
        print(f"ERROR: live model not found at {LIVE_MODEL}", file=sys.stderr)
        return 1

    print("Launching Excel via COM...")
    excel = win32.gencache.EnsureDispatch("Excel.Application")
    excel.Visible = False
    excel.DisplayAlerts = False

    captured: dict[str, dict] = {}
    wb = None
    try:
        print(f"Opening {LIVE_MODEL.name}...")
        wb = excel.Workbooks.Open(str(LIVE_MODEL), ReadOnly=False, UpdateLinks=0)
        ws = wb.Worksheets("Summary")
        original_d4 = ws.Range("D4").Value
        print(f"  D4 was: {original_d4!r}")

        for label, value in SCENARIO_VALUES:
            print(f"  Setting D4 = {value!r} and recalculating...")
            ws.Range("D4").Value = value
            excel.CalculateFullRebuild()
            captured[label] = capture_outputs(ws)
            print(f"    {label}: revenue 2026={captured[label]['revenue'][4]:,.0f}M  "
                  f"ebitda 2026={captured[label]['ebitda'][4]:,.0f}M  "
                  f"eps 2026=${captured[label]['eps'][4]:.2f}")

        # Restore original
        print(f"  Restoring D4 to {original_d4!r}")
        ws.Range("D4").Value = original_d4
        excel.CalculateFullRebuild()

        # Close WITHOUT saving
        wb.Close(SaveChanges=False)
        wb = None
    finally:
        if wb is not None:
            try:
                wb.Close(SaveChanges=False)
            except Exception:
                pass
        excel.Quit()

    # Write scenarios.json
    out = {
        "_note": "Regenerated by regenerate_scenarios.py — flips Summary!D4 to capture each scenario.",
        "Base": {"use_model": True, **captured["Base"]},
        "Bull": {"use_model": False, **captured["Bull"]},
        "Bear": {"use_model": False, **captured["Bear"]},
    }
    SCENARIOS_FILE.write_text(json.dumps(out, indent=2))
    print(f"\nWrote {SCENARIOS_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
