[theme]
primaryColor = "#303f55"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f6f9"
textColor = "#1a2230"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
